### ISSUE TITLE
Comment layout looks broken when mentioning Arabic nickname

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2400]
Check the comment on one of the translations
https://pontoon.mozilla.org/ar/firefox/browser/browser/aboutPocket.ftl/?search=pocket-panel-signup-signup-firefox&string=224278

<img width="1065" alt="Schermata 2022-01-07 alle 16 37 42" src="https://user-images.githubusercontent.com/3644868/148567649-069d6299-8313-4593-b651-27f864ec19fe.png">

The mention is at the beginning, but it's displayed at the rightmost end. Also, typing after that is really weird (try typing @, then select Safa's nickname, then type something).

**Comment by SafaAlfulaij** [comment]
I intentionally chose to have an Arabic name on Pontoon to trigger these bugs, alongside with using my lovely native language :)

The easy solution is to wrap mentions in a FSI/PDI (to accommodate for whatever users can come up with in their names).

Fast hack:

```css
.comments-list .comment .container .content p {
  unicode-bidi: plaintext;
}

.comments-list .comment .container .content a[href^="/contributors/"]:not(.comment-author)::before {
    content: "\2068";
}

.comments-list .comment .container .content a[href^="/contributors/"]:not(.comment-author)::after {
    content: "\2069";
}

/* Optional, I just think it would be better to have the comment body under the name of the person. */
.comments-list .comment .container .content .Linkify {
  display: block;
}

```

**Comment by mathjazz** [comment]
@SafaAlfulaij Could the following rule be used instead of the 2nd and the 3rd rule in your proposal?

```css
.comments-list .comment .container .content a[href^="/contributors/"]:not(.comment-author) {
  unicode-bidi: isolate;
}
```

And, is the 1st rule (`unicode-bidi: plaintext`) effectively the same as removing `dir="auto"` on the parent element?

Thanks for your help!
