### ISSUE TITLE
Missing translations after sync

### ISSUE THREAD

**Issue by sfriedel** [mozilla/pontoon#3572]
I noticed some weird sync behavior in one of our projects after updating pontoon recently.
After syncing the project, pontoon considers some translations in a single locale (`de`) missing, even though the project was 100% translated previously. Also, the second translated locale (`es`) is missing the messages that pontoon considers missing in DE completely.

This is how it looks in the project locales listing (all rows are forced to hovered styles to show the numbers):

![Image](https://github.com/user-attachments/assets/bd860535-5d88-4487-ac37-448298335f57)

I also tried a forced sync via manage.py but when I run that, pontoon pushes a commit that empties the `de` translations that it considered missing:

![Image](https://github.com/user-attachments/assets/5f90baa3-2d09-4dfb-9805-245eb85ef8de)

Project configuration in Pontoon:

![Image](https://github.com/user-attachments/assets/03ada13c-7cd5-44e4-85c9-5205b2ff7e1d)

And the l10n.toml in the project:

```toml
basepath = "."
locales = ["en", "es", "de"]

[[paths]]
reference = "translations/wordpress.pot"
l10n = "translations/wordpress/wordpress-es_ES.po"
locales = ["es"]

[[paths]]
reference = "translations/wordpress.pot"
l10n = "translations/wordpress/wordpress-de_DE.po"
locales = ["de"]

[[paths]]
reference = "translations/wordpress-react.pot"
l10n = "translations/wordpress-react/wordpress-react-{locale}.po"
```

I realize this is a very unusual configuration. The goal was to combine the "de" and "es" locales from one part of the application with the "de_DE" and "es_ES" locales of another part in a single pontoon project.

The configuration was working fine with previous versions of pontoon (last one used was 5bb087761425e3eebd2b173a150ac33d0754a21c before the update) and I'd mostly like to confirm if a configuration like this would be expected to work or not.

The repo with the translation for reproduction is available at https://github.com/sfriedel/pontoon-sync-error-reproduction
